In [92]:
print("Hello World")

Hello World


In [93]:
import numpy as np

$ git rm numpy.ipynb --cached

SyntaxError: invalid syntax (4203499525.py, line 3)

### Exercise 1

Given, there are 5 numbers in the data set: (8, 12, 16, 24, 4). What is the standard deviation? And, what will be the sum of deviations of individual data points from their mean?

In [ ]:
List1 = (8, 12, 16, 24, 4)

In [ ]:
print("Mean: ", np.mean(List1))

Mean:  12.8


In [ ]:
print("Variance: ", np.var(List1))
#Variance = Sum of all deviations from the mean

Variance:  47.36


In [ ]:
print("Standard Deviation:",np.sqrt(np.var(List1)))

Standard Deviation: 6.881860213634101


In [ ]:
print("Standard Deviation:", np.std(List1))

Standard Deviation: 6.881860213634101


### Exercise 2:

Question: If some outliers are introduced to the dataset, what will happen to the Standard Deviation? Will it increase, decrease or remain the same? 

Outliers will increase the Standard Deviation. Less Outlier = less Deviation

### Exercise 3:

Answer F: B + C

### Exercise 4:

Assume the data are distributed as follows:

[10, 10, 10, 10, 11, 11, 12, 13, 14 ]

[15, 15, 15, 16, 16, 16, 16, 16, 17, 18, 19, 19]

[20, 20, 20, 21, 21, 21, 21, 21, 22, 22, 22, 23, 23, 23, 24, 24, 24]

[26, 26, 26, 26, 26, 26, 26, 27, 27, 27, 27, 29, 29, 29, 29, 29, 29, 29, 29, 29]

[30, 30, 30, 30, 30, 31, 31, 32, 32, 33, 33, 34, 34]

[35, 35, 35, 37, 37, 37, 37, 39, 39, 39]

[40, 40, 43, 43, 44, 44]

[46, 46, 46, 47, 49]

[52, 53, 54]

Find the Median



In [ ]:
my_List2 =  ([10, 10, 10, 10, 11, 11, 12, 13, 14 ],
[15, 15, 15, 16, 16, 16, 16, 16, 17, 18, 19, 19],
[20, 20, 20, 21, 21, 21, 21, 21, 22, 22, 22, 23, 23, 23, 24, 24, 24],
[26, 26, 26, 26, 26, 26, 26, 27, 27, 27, 27, 29, 29, 29, 29, 29, 29, 29, 29, 29],
[30, 30, 30, 30, 30, 31, 31, 32, 32, 33, 33, 34, 34],
[35, 35, 35, 37, 37, 37, 37, 39, 39, 39],
[40, 40, 43, 43, 44, 44],
[46, 46, 46, 47, 49],
[52, 53, 54])



In [ ]:
new_List = np.concatenate(my_List2)

print(new_List)



[10 10 10 10 11 11 12 13 14 15 15 15 16 16 16 16 16 17 18 19 19 20 20 20
 21 21 21 21 21 22 22 22 23 23 23 24 24 24 26 26 26 26 26 26 26 27 27 27
 27 29 29 29 29 29 29 29 29 29 30 30 30 30 30 31 31 32 32 33 33 34 34 35
 35 35 37 37 37 37 39 39 39 40 40 43 43 44 44 46 46 46 47 49 52 53 54]


In [ ]:
median = np.median(new_List)

print(median)

27.0


### Exercise 5, 6 & 7

5) What is the shape of the distribution?

Answer: Positively Skewed Distribution



6) What would you consider to be the most appropriate measure of the center for this data?

Mean as it shows the average salary 

7) If Y axis represents the number of individuals and X axis – salary of the individual in thousands. How many individuals have salary less than 10 thousands? (no Numpy)

11 + 24 = 35 People





### Exercise 8

We have a set of positive numbers. If a single value of the set is altered what must change?

A) Mean
B) Median
C) Mode
D) All of these

a) mean will always change since the average consists of all values
b) the median does not necessarily has to change since it only represents the middle value (which can also occur several times)
c) the mode does not necessarily has to change since it only represents the most frequent value (which can also occur several times)

Hint: try to create a Numpy array and calculate mean median and mode, then alter it and see what changes

### Exercise 9

The chart shows hourly consultancy rate of 10 people.

Calculate the standard deviation of the salaries of the 10 employees.

In [ ]:
salary = [25, 25, 25, 40, 40, 35, 50, 50, 50, 50]

In [ ]:
import numpy as np

print("Standard Deviation: ",np.std(salary))

Standard Deviation:  10.44030650891055


### Exercise 10 

Which of the following random variables is discrete?

discrete = cannot be broken down - hence needs to be full number

A) the length of time a battery lasts 

B) the number of pens purchased by a student in a year - number of pens is the answer as the student only buys whole pens and does not purchase fractions 

C) the percentage of cows in a cattle firm that have been vaccinated

D) the distance between a pair of towns



### Exercise 11

Which of the below normal distributions will have the greatest spread?

A) mu=5, sigma =1.5

B) mu=10, sigma =1.0

C) mu=5, sigma =1.65

D) mu=8, sigma =1.2

E) mu=10, sigma =1.6

Answer: C) As sigma determines the spread and c) has the highest sigma value 

# Extra Exercises

In [ ]:
#### 1. Import the numpy package under the name `np` (★☆☆)

import numpy as np

In [ ]:
#### 2. Print the numpy version and the configuration (★☆☆)

print(np.version), print(np.show_config)

<module 'numpy.version' from '/Users/Lucasmeissner/anaconda3/lib/python3.11/site-packages/numpy/version.py'>
<function show at 0x10a4ecd60>


(None, None)

In [ ]:
#### 3. Create a null vector of size 10 (★☆☆)

array_1= np.zeros(10)

In [ ]:
#### 4. How to find the memory size of any array (★☆☆)

def memory(List):
    print("Size of the array:",List)
    print("Memory Size of one array element in bytes:",List.itemsize)

# memory size of numpy array in bytes

    print("Memory size of numpy array in bytes:",
      List.size * List.itemsize)



In [ ]:
array_example = np.zeros(20)
print(array_example)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [ ]:
memory(array_example)

Size of the array: [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
Memory Size of one array element in bytes: 8
Memory size of numpy array in bytes: 160


In [ ]:
#### 5. How to get the documentation of the numpy add function from the command line? (★☆☆)

np.info(np.add)

add(x1, x2, /, out=None, *, where=True, casting='same_kind', order='K', dtype=None, subok=True[, signature, extobj])

Add arguments element-wise.

Parameters
----------
x1, x2 : array_like
    The arrays to be added.
    If ``x1.shape != x2.shape``, they must be broadcastable to a common
    shape (which becomes the shape of the output).
out : ndarray, None, or tuple of ndarray and None, optional
    A location into which the result is stored. If provided, it must have
    a shape that the inputs broadcast to. If not provided or None,
    a freshly-allocated array is returned. A tuple (possible only as a
    keyword argument) must have length equal to the number of outputs.
where : array_like, optional
    This condition is broadcast over the input. At locations where the
    condition is True, the `out` array will be set to the ufunc result.
    Elsewhere, the `out` array will retain its original value.
    Note that if an uninitialized `out` array is created via the default
    ``out

In [ ]:
y = np.zeros(10)

y[4]= 1

print(y)


[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


In [ ]:
#### 7. Create a vector with values ranging from 10 to 49 (★☆☆)

array_2 = np.arange(10,50)


In [115]:
#### 8. Reverse a vector (first element becomes last) (★☆☆)

array_2

res = array_2[::-1]
print(res)

[49 48 47 46 45 44 43 42 41 40 39 38 37 36 35 34 33 32 31 30 29 28 27 26
 25 24 23 22 21 20 19 18 17 16 15 14 13 12 11 10]


In [123]:
#### 9. Create a 3x3 matrix with values ranging from 0 to 8 (★☆☆)

array_3=np.arange(0,9)

print(array_3.reshape(3,3))



[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [128]:
#### 10. Find indices of non-zero elements from [1,2,0,0,4,0] (★☆☆)

array_4= [1,2,0,0,4,0]
x = np.nonzero(array_4)
print(x)



(array([0, 1, 4]),)


In [130]:
#### 11. Create a 3x3 identity matrix (★☆☆)

np.identity(3)


array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [134]:
#### 12. Create a 3x3x3 array with random values (★☆☆)

array_5=np.random.randint(0,1000, size=(3,3))
array_5


array([[691, 596,  14],
       [167, 137,  56],
       [228, 137, 764]])

In [138]:
#### 13. Create a 10x10 array with random values and find the minimum and maximum values (★☆☆)

array_6=np.random.randint(0,1000, size=[10,10])

print(array_6)
print("Max: ",np.max(array_6))
print("Min: ",np.min(array_6))

[[495 305 310 895 975 832  49 513 292 108]
 [573  68 758 152 103 874 297 226 733 431]
 [283 371 943 788 255 643 231 567 607 894]
 [ 23 509 189 589 482 129 586 167 151 421]
 [772 416 653 370 629  55 730  69 352  80]
 [648 237 558 851 373 592 620 364 372 297]
 [244  57 748  79 803 465 185 815 617 981]
 [904 562 414 538   6 700 904 342  50 867]
 [155 315 607 549 142 136  90 656 134 795]
 [648 332 710 498 214 972 413 900 763 927]]
Max:  981
Min:  6
